# More details about each entry are in cross_validation_cme_alone.yaml
defaults:
  - _self_
  - data/dataset: SWAN/flare_cme_assoc
  - data/data_loader: default_sampler
  - optimizer: adam
  - model: rotary_transformer_forecast_model
  - metrics: binary_classification # Must be before logger
  - plotting: binary_classification # Must be before logger
  - logger: wandb
  - loss: bcewithlogits
  - scheduler: cycliclr
  - local: local

hydra:
  run:
    dir: ./out/${problem_type}/${data.main.T}/${model.name}
  job:
    chdir: true # So working directory is in the output directory

cross_validation:
  db_path: ../../results.db # db where results about the run are stored. relative to hydra.run.dir
  table: ${model.name}_${eval:'str(int(${data.main.T}))'} # table where results are stored
  checkpoints_extra_sub_folders: [] # if any, subfolder created for each entry. checkpoints stored there
  use_checkpoints: true # whether checkpoints are to be loaded before training
  checkpoints_db_path: "/unsafe2/jhc/cme_flare_forecast/out/flare_forecast/results.db" # if so, this is pointing to a db that tells the code where to find the checkpoints
  checkpoints_table: "rotary_transformer_24" # and the table to use

project: "Final Flare CME Assoc."
problem_type: "flare_cme_assoc"
seed: 011234581321

shared:
  class_names: ["CME", "No CME"]
  prob_threshold: 0.5
  device: "cuda:1"
  scheduler_base_lr: 0.00001 # Minimum learning rate
  scheduler_max_lr: 0.0001 # Maximum learning rate
  scheduler_step_size_up: 6 # Cycle up every 3 epochs
  scheduler_mode: "triangular2" # Use a decaying triangular shape

train:
  n_epochs: 120
  checkpoint_every_n_epochs: 2
  load_checkpoint: true
  checkpoint_path: ""
  early_stop:
    enabled: true
    args:
      patience: 20
      per_min_delta: 0.01
      criterion: "min"

data:
  batch_size: 256
  num_workers: 6
  main:
    T: 24
    L: 24
    S: 0.2
    B: 0
    C: 0.4
    MIN_FLARE_CLASS: 30
    ALLOW_OVERLAPS: 1
    padding_strategy: "zero"
    keywords: "default"
    use_PCA: false
    n_PCA_components: 0
