# More details about each entry are in cross_validation_cme_alone.yaml
defaults:
  - _self_
  - data/dataset: SWAN/flare_class
  - data/data_loader: default_sampler
  - optimizer: adam
  - model: rotary_transformer_forecast_model
  - metrics: binary_classification # Must be before logger
  - plotting: binary_classification # Must be before logger
  - logger: wandb
  - loss: bcewithlogits
  - scheduler: cycliclr
  - local: local

hydra:
  run:
    dir: ./out/${problem_type}/${data.main.T}/${model.name}
  job:
    chdir: true # So working directory is in the output directory

cross_validation:
  db_path: ../../results.db
  table: ${model.name}_${eval:'str(int(${data.main.T}))'}
  checkpoints_extra_sub_folders: []
  use_checkpoints: false
  checkpoints_db_path: "/home/jhc/cmeml/out/flare_forecast/results.db"
  checkpoints_table: "donahuetransformerforecast_24_train_active_validate_all_not_use_hist_params"

project: "Final Flare Class CV"
problem_type: "flare_forecast"
seed: 011234581321

shared:
  class_names: [">M Flare", "No >M Flare"]
  prob_threshold: 0.5
  device: "cuda:1"
  scheduler_base_lr: 0.000005 # Minimum learning rate
  scheduler_max_lr: 0.00002 # Maximum learning rate
  scheduler_step_size_up: 3 # Cycle up every 3 epochs
  scheduler_mode: "triangular2" # Use a decaying triangular shape

train:
  n_epochs: 40
  checkpoint_every_n_epochs: 2
  load_checkpoint: false
  checkpoint_path: ""
  early_stop:
    enabled: true
    args:
      patience: 10
      per_min_delta: 0.01
      criterion: "min"

data:
  batch_size: 256
  num_workers: 6
  main:
    T: 24
    L: 24
    S: 0.2
    B: 0
    C: 0.4
    MIN_FLARE_CLASS: 30
    ALLOW_OVERLAPS: 1
    padding_strategy: "zero"
    keywords: "default"
    use_PCA: false
    n_PCA_components: 0
